language: node_js
node_js:
- lts/dubnium
- stable
script: npm run coverage && npm run flow
after_success: npm run coveralls
deploy:
  provider: npm
  email: jakepolatty@gmail.com
  api_key:
    secure: m0htZDKNmqKBpK5xjWurVWXpZMLrk8aEbF8jDQVth2C2nse/g2BftmYbYNxRrJoCCbCpAYi90prbSZE/6nNOjfFJnz/0ihWDcLVO5ggceuPcUVe1csgnst1R+GACMcVI9VJeuFYOvMEjGZ5Q5SVsZAmghQVgwBhLxo46BzoDXcPDCG8yYj4dlORDrVjMPkBP0t5jxQxhv3USe3rXbR0H6nv9HQtlpXuaQleRAWmYv2pyWJUyFGaQJ3DVdPMOdjB9XwpcjpJPhit65Fe6XvcYOWWE/gy8Scq46TRpOoraqlkwgG06HZawd/gEf+FeLEK4VFJlfg9OKTSichj4yMBPGcYk5vqbVHNvaXj/7OG3GApHy+43k7u1NVpcU9MjSX8ZB2cqN5y7Z0KHfFTDRLnIAqZ38ndHc2O+1SfnIX9FH8UJ5LqG/iAMglU8NirrHGemqmzlSPLq6zVEQ+BTRpSfWuxGgfkRF5iLDvFkfMfwLW3ZiGmjFGJtalKQWjTi3MIYsgU+pDNe1/zmpvSz3ANJs6Dm1FWG4pw5FXVPWT/dYz57YvLTMtrw5kiUzSunQbisF8KCDzNeDyAU0cm4baKieNcW4cE+2RsHNGAm8dHDoBvzXv/7bTTOqjAHX/7MGD2i7zyoGYxKNjXFMOb7dZI6Gdoc2dfEQ3wxFhDLRlMbPiM=
  skip_cleanup: true
  on:
    tags: true
    branch: master
