language: node_js
node_js:
- lts/dubnium
- stable
script: npm run coverage && npm run flow
after_success: npm run coveralls && npm run build
deploy:
  provider: npm
  email: jakepolatty@gmail.com
  api_key:
    secure: kBlnPeZ5RPqZUpMrzZLzuM0MOyPCiXoCskG5kCNazE8t1MhX0s+ANNvmh6lcus7GNaoBEIZZrWk5rnHgYDSGexgFaqG8nIQt4R4iKnnhXRHRBIen5lQ5f+DuR3DHaDGVx6CImb6P8qfhhBRwydLNh8YgYORokD+G2btfEIGML+u2yQ9LPYiouSICdzut3Gc7ehhufVrzKdrJnaRP3yRRt0NLIVDnlUfCpxcbpUpP105+A0gCM7M5K4+v80fYS/aEflbouuASvDHZ4Vs9XqUqh9hxLm3+0E6M/sMvfCsVjQZnfji20adrHRBPo2OhJj5Sd/51WBbd5X/9qWF9d0HuLImP6xg6pKTkF8vIZVOwGYWBBR7lAlfnH6JwA9MGbLNnle0myWPUwWoO4W8nr2ZCxgWsHMGe/yYrH/pJyHud/HcDyO7muzd1aYrZ8OilHJtKE4Oi2AfqMdqBJ5Y2Pc/UXoCkJc10FNyCcz1rmePsKArmjkmpQ/muposOHwTQ3cdGYlN2eSgRTuXB0vmCUTyQni0XMbD7NSQ59NE0NRT/iBgB7tzJKJRJ4Zs7ywaDTEnjRJanMgiaGaow1em/Bp3UtlKBBlIraWaTFnb0fImQ31xth1VrlmONq9XsCu0OcA3zV2hKicNz8lp/dgAWRoGyxRA17YhN9uNrJjlgzIlVKVA=
  skip_cleanup: true
  on:
    tags: true
    branch: master
